# Generated by Django 3.2.15 on 2022-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query_type',
            field=models.BooleanField(blank=True, choices=[(0, 'Question'), (1, 'Sponsorship'), (2, 'Other')], default=0, null=True),
        ),
    ]
