# Generated by Django 3.2.15 on 2022-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0002_auto_20220910_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Christian Brown', max_length=40),
        ),
    ]
