# Generated by Django 3.2.15 on 2022-09-21 08:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0003_alter_contact_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
