# Generated by Django 3.2.15 on 2022-09-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0007_alter_post_championship_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='eventName',
            new_name='event_name',
        ),
    ]
