# Generated by Django 3.2.15 on 2022-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0009_auto_20221001_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='class_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='overall_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
