# Generated by Django 3.2.15 on 2022-10-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0011_alter_like_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='reaction',
            field=models.BooleanField(choices=[(0, 'Like'), (1, 'Unlike')], default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='associated_club',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='entry_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
