# Generated by Django 3.2.15 on 2022-10-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0012_auto_20221014_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='reaction',
        ),
    ]
