# Generated by Django 3.2.15 on 2022-10-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0013_remove_like_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reaction',
            field=models.BooleanField(choices=[(0, 'Like'), (1, 'Unlike')], default=None),
        ),
    ]
