# Generated by Django 3.2.15 on 2022-10-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallyApp', '0015_alter_like_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='reaction',
            field=models.CharField(default='Liked', max_length=10),
        ),
    ]
